[2021-04-23 21:03:48,442] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.run_recent_played_ingestion_pypark 2021-04-23T19:00:00+00:00 [queued]>
[2021-04-23 21:03:48,468] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.run_recent_played_ingestion_pypark 2021-04-23T19:00:00+00:00 [queued]>
[2021-04-23 21:03:48,471] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 21:03:48,473] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-23 21:03:48,474] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 21:03:48,496] {taskinstance.py:1063} INFO - Executing <Task(DataprocSubmitPySparkJobOperator): run_recent_played_ingestion_pypark> on 2021-04-23T19:00:00+00:00
[2021-04-23 21:03:48,520] {standard_task_runner.py:52} INFO - Started process 668 to run task
[2021-04-23 21:03:48,531] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'recent_played_ingestion', 'run_recent_played_ingestion_pypark', '2021-04-23T19:00:00+00:00', '--job-id', '44', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/recent_played_ingestion.py', '--cfg-path', '/tmp/tmp0n4i0m0b', '--error-file', '/tmp/tmp7ttzzvyk']
[2021-04-23 21:03:48,537] {standard_task_runner.py:77} INFO - Job 44: Subtask run_recent_played_ingestion_pypark
[2021-04-23 21:03:48,643] {logging_mixin.py:104} INFO - Running <TaskInstance: recent_played_ingestion.run_recent_played_ingestion_pypark 2021-04-23T19:00:00+00:00 [running]> on host 760ffd3d790b
[2021-04-23 21:03:48,806] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=recent_played_ingestion
AIRFLOW_CTX_TASK_ID=run_recent_played_ingestion_pypark
AIRFLOW_CTX_EXECUTION_DATE=2021-04-23T19:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-23T19:00:00+00:00
[2021-04-23 21:03:48,812] {dataproc.py:981} INFO - Submitting pyspark_job job run_recent_played_ingestion_pypark_20210423_107ce988
[2021-04-23 21:03:49,516] {taskinstance.py:1455} ERROR - 404 Not found: Cluster projects/spotimood-dev/regions/europe-west2/clusters/ephemeral-recent-played-spark-cluster-20210423
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 73, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/airflow/.local/lib/python3.6/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.NOT_FOUND
	details = "Not found: Cluster projects/spotimood-dev/regions/europe-west2/clusters/ephemeral-recent-played-spark-cluster-20210423"
	debug_error_string = "{"created":"@1619211829.513409200","description":"Error received from peer ipv4:142.250.184.10:443","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Not found: Cluster projects/spotimood-dev/regions/europe-west2/clusters/ephemeral-recent-played-spark-cluster-20210423","grpc_status":5}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 1545, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 983, in execute
    project_id=self.project_id, job=self.job["job"], location=self.region
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 425, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 819, in submit_job
    metadata=metadata,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/dataproc_v1beta2/gapic/job_controller_client.py", line 279, in submit_job
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 75, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.NotFound: 404 Not found: Cluster projects/spotimood-dev/regions/europe-west2/clusters/ephemeral-recent-played-spark-cluster-20210423
[2021-04-23 21:03:49,546] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=recent_played_ingestion, task_id=run_recent_played_ingestion_pypark, execution_date=20210423T190000, start_date=20210423T210348, end_date=20210423T210349
[2021-04-23 21:03:49,610] {local_task_job.py:146} INFO - Task exited with return code 1
