[2021-04-23 14:05:55,873] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.run_recent_played_classification_pypark 2021-04-23T12:00:00+00:00 [queued]>
[2021-04-23 14:05:55,916] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: recent_played_ingestion.run_recent_played_classification_pypark 2021-04-23T12:00:00+00:00 [queued]>
[2021-04-23 14:05:55,917] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 14:05:55,918] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-04-23 14:05:55,919] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-23 14:05:55,935] {taskinstance.py:1063} INFO - Executing <Task(DataprocSubmitPySparkJobOperator): run_recent_played_classification_pypark> on 2021-04-23T12:00:00+00:00
[2021-04-23 14:05:55,941] {standard_task_runner.py:52} INFO - Started process 40 to run task
[2021-04-23 14:05:55,947] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'recent_played_ingestion', 'run_recent_played_classification_pypark', '2021-04-23T12:00:00+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/recent_played_ingestion.py', '--cfg-path', '/tmp/tmposn14gsp', '--error-file', '/tmp/tmp64k1zado']
[2021-04-23 14:05:55,951] {standard_task_runner.py:77} INFO - Job 6: Subtask run_recent_played_classification_pypark
[2021-04-23 14:05:56,052] {logging_mixin.py:104} INFO - Running <TaskInstance: recent_played_ingestion.run_recent_played_classification_pypark 2021-04-23T12:00:00+00:00 [running]> on host f45b7a3b369e
[2021-04-23 14:05:56,133] {taskinstance.py:1455} ERROR - unexpected '}', expected ')'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1249, in _prepare_and_execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1750, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 859, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 872, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 923, in render_template
    return [self.render_template(element, context, jinja_env) for element in content]
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 923, in <listcomp>
    return [self.render_template(element, context, jinja_env) for element in content]
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 909, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
[2021-04-23 14:05:56,147] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=recent_played_ingestion, task_id=run_recent_played_classification_pypark, execution_date=20210423T120000, start_date=20210423T140555, end_date=20210423T140556
[2021-04-23 14:05:56,232] {local_task_job.py:146} INFO - Task exited with return code 1
